# Generated by Django 5.0.3 on 2024-03-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usable_amount',
            field=models.IntegerField(default=0),
        ),
    ]
