# Generated by Django 5.0.3 on 2024-03-23 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('deliveryPoint', models.CharField(max_length=150)),
                ('deliveryPoint2', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total_paid', models.IntegerField()),
                ('receipt_No', models.CharField(blank=True, max_length=200)),
                ('billing_status', models.BooleanField(default=False)),
                ('return_date', models.DateField()),
                ('return_status', models.BooleanField(default=False)),
                ('purchase_cost', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leased', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='LeasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_rate', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Book_Lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', to='orders.book_lease')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leased_items', to='store.product')),
            ],
        ),
    ]
