# Generated by Django 5.0.3 on 2024-03-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_lease',
            name='delivered_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book_lease',
            name='leased_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book_lease',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
