# Generated by Django 5.0.3 on 2024-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_book_lease_delivered_date_book_lease_leased_weeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lease',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_lease',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
